Repository EyobDejene/TechTeam, pull requests merged in 2019-06, with the labels that each got.

#11 Delete user 💀
  app.js
  routes/deleteProfile.js
  routes/deleting.js
  views/deleteProfile.ejs
  views/editProfile.ejs
  views/overview.ejs
Labels: enhancement

#14 :fire: Removed a testing button that made it to the live application.
  app.js
  models/login.model.js
  models/registration.model.js
  models/users.model.js
  package.json
  public/images/icons/pencil.png
  public/images/icons/refresh.svg
  public/javascripts/modules/explore.js
  public/javascripts/script.js
  public/stylesheets/style.css
  public/upload/21e2644cb714ca0fec3f63d10f9e7068
  public/upload/a55d8dd9505794ba09849a52ed580fea
  public/upload/profile_daniel.jpg
  public/upload/profile_mark.jpg
  public/upload/profile_max.jpg
  public/upload/profile_niels.jpg
  public/upload/profile_simon.jpg
  public/upload/profile_tim.jpg
  routes/deleteProfile.js
  routes/deleting.js
  routes/editProfile.js
  routes/index.js
  routes/login.js
  routes/onboarding.js
  routes/overview.js
  routes/registration.js
  views/deleteProfile.ejs
  views/editProfile.ejs
  views/index.ejs
  views/layouts/layout.ejs
  views/onboarding.ejs
  views/overview.ejs
  views/registration.ejs
Labels: bug, invalid

#15 Deleted 'manage users' :fire:
  views/overview.ejs
Labels: bug, invalid

#16 Session Destroyed
  public/stylesheets/style.css
  routes/deleting.js
  views/deleteProfile.ejs
  views/editProfile.ejs
Labels: bug, invalid

#18 🐛 Fixed a bug that affects filtering matches
  routes/overview.js
Labels: bug

#22 🐛 fixing a bug
  routes/index.js
  routes/overview.js
Labels: bug

#24 Bugs fix profile on dev branch
  public/upload/4e8f34dc1b3baa81f621ad46e450c1ae
  routes/editProfile.js
  views/editProfile.ejs
Labels: bug, enhancement

#30 Added styling to upload button in editProfile
  README.md
  app.js
  public/images/icons/add.png
  public/stylesheets/style.css
  routes/cancel.js
  views/editProfile.ejs
Labels: enhancement

#27 Password hashing
  README.md
  models/registration.model.js
  models/users.model.js
  package.json
  routes/onboarding.js
  routes/registration.js
  views/overview.ejs
  views/registration.ejs
Labels: Update, enhancement, good first issue

#34 Changes to HTML and CSS considering deleting your account.
  public/stylesheets/style.css
  views/deleteProfile.ejs
Labels: Markup

#38 🐛 filtering setting will be readout of the url
  public/javascripts/filter.js
  public/javascripts/script.js
  routes/overview.js
  views/overview.ejs
Labels: bug, enhancement

#49 💄 added loader when refreshing location
  public/javascripts/script.js
  public/stylesheets/style.css
  views/index.ejs
Labels: enhancement
